                                            Assignment Numpy

Theoretical Questions:

 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

 Ans: NumPy, which stands for Numerical Python, is a fundamental package for scientific computing and data analysis in Python. Its main purpose is to provide a powerful N-dimensional array object and tools for working with these arrays efficiently. Here are some key advantages and enhancements that NumPy brings to Python for numerical operations:

### Purpose of NumPy
1. **N-dimensional Arrays**: NumPy introduces the `ndarray` object, a fast and flexible container for large datasets in Python. This allows for multi-dimensional data representation (1D, 2D, 3D, etc.), which is crucial for scientific applications.

2. **Numerical Computing**: It provides a comprehensive set of mathematical functions and operations that allow for efficient numerical computations, such as linear algebra, Fourier transforms, and random number generation.

3. **Interoperability**: NumPy arrays can interact seamlessly with other libraries and tools in the scientific computing ecosystem, including SciPy, pandas, and matplotlib, making it a foundational library for many scientific applications.

### Advantages of NumPy
1. **Performance**: NumPy is implemented in C and Fortran, enabling it to execute operations at much higher speeds than native Python lists, particularly for large datasets. This is due to its optimized performance for array operations, which can often be executed in a vectorized manner.

2. **Memory Efficiency**: NumPy arrays consume less memory compared to traditional Python lists because they store elements of the same data type, allowing for more efficient data storage.

3. **Broadcasting**: NumPy supports broadcasting, a powerful mechanism that allows arithmetic operations on arrays of different shapes and sizes, simplifying code and improving performance.

4. **Rich Functionality**: NumPy includes a wide range of mathematical functions, such as statistical functions, linear algebra routines, and capabilities for Fourier transforms, making it a versatile tool for data analysis.

5. **Ease of Use**: NumPy provides a user-friendly interface for numerical operations, allowing users to write clear and concise code for complex mathematical computations.

6. **Integration**: NumPy integrates well with C/C++ and Fortran code, enabling the inclusion of optimized routines from other programming languages, which can be beneficial for performance-critical applications.

### Enhancements to Python's Capabilities
- **Vectorization**: NumPy allows for element-wise operations on arrays without the need for explicit loops, significantly speeding up computations and improving code readability.
- **Advanced Indexing and Slicing**: It provides sophisticated techniques for accessing and manipulating array data, enabling more complex data analysis tasks.
- **Data Manipulation**: With tools for reshaping, joining, and splitting arrays, NumPy simplifies data preprocessing steps essential for analysis.

Overall, NumPy enhances Python's capabilities for numerical operations, making it an essential library for scientists, engineers, and data analysts who require high-performance computing and data manipulation tools.

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

Ans: The np.mean() and np.average() functions in NumPy are both used to compute averages, but they have different functionalities and use cases. Here’s a comparison:

np.mean()
Purpose: Computes the arithmetic mean (average) of array elements along a specified axis.
Syntax: np.mean(a, axis=None, dtype=None, out=None, keepdims=False)
Behavior:
Takes an array as input and returns the mean of the values along the specified axis.
Does not support weighting; all elements are treated equally.
Example:

In [ ]:
import numpy as np

data = np.array([1, 2, 3, 4])
mean_value = np.mean(data)  # Output: 2.5


np.average()
Purpose: Computes the weighted average of array elements. If no weights are provided, it behaves like np.mean().
Syntax: np.average(a, axis=None, weights=None, returned=False)
Behavior:
Can take an optional weights parameter, allowing for the computation of a weighted average.
If weights are provided, they should be the same shape as the input array or broadcastable to it.
Example:

In [ ]:
data = np.array([1, 2, 3, 4])
weights = np.array([0.1, 0.2, 0.3, 0.4])
weighted_average = np.average(data, weights=weights)  # Output: 3.0


When to Use Each
Use np.mean():

When you need a simple average of the data without any weights.
When you want a concise and straightforward function for computing the mean.
Use np.average():

When you require a weighted average, where some elements contribute more to the average than others.
When you want to leverage the functionality for specifying weights in your calculations.
Summary
In essence, use np.mean() for standard average calculations and np.average() when you need to account for the importance of certain elements through weighting.





 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

Ans: Reversing a NumPy array can be done using slicing techniques. Depending on whether you want to reverse a 1D or 2D array, the approach differs slightly. Here are methods for reversing arrays along different axes, along with examples.

Reversing a 1D Array
For a 1D array, you can simply use slicing with the step -1.

Example:

In [ ]:
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Reverse the array
reversed_1d = array_1d[::-1]
print(reversed_1d)  # Output: [5 4 3 2 1]


Reversing a 2D Array
For a 2D array, you can reverse the array along specific axes. You can reverse along rows (axis 0) or columns (axis 1).

Example of Reversing Along Rows (Axis 0)

In [ ]:
# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Reverse the array along rows (axis 0)
reversed_rows = array_2d[::-1, :]
print(reversed_rows)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]


Example of Reversing Along Columns (Axis 1)

In [ ]:
# Reverse the array along columns (axis 1)
reversed_columns = array_2d[:, ::-1]
print(reversed_columns)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]


Summary
For 1D arrays, you can reverse the array using array[::-1].
For 2D arrays, use:
array[::-1, :] to reverse along rows (axis 0).
array[:, ::-1] to reverse along columns (axis 1).
These methods utilize NumPy’s slicing capabilities, allowing for efficient and straightforward array manipulation.





 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

 Ans: In NumPy, you can determine the data type of the elements in an array using the .dtype attribute. Here’s how you can do it and a discussion on the importance of data types in memory management and performance.

Determining Data Type
To check the data type of elements in a NumPy array, you can use the following approach:

Example:

In [ ]:
import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3, 4])

# Determine the data type
data_type = array.dtype
print(data_type)  # Output: int64 (or int32, depending on the system)


You can also create an array with a specific data type by using the dtype parameter during array creation:

In [ ]:
# Create an array with a specified data type
array_float = np.array([1, 2, 3], dtype=np.float32)
print(array_float.dtype)  # Output: float32


Importance of Data Types
Memory Management:

Different data types consume different amounts of memory. For instance, an int32 takes up 4 bytes, while an int64 takes 8 bytes. Choosing the appropriate data type can help optimize memory usage, especially when dealing with large datasets.
Using smaller data types (like float32 instead of float64) can significantly reduce memory consumption while still providing adequate precision for many applications.
Performance:

Operations on arrays with smaller data types often execute faster due to reduced data transfer and processing overhead. For example, arithmetic operations on int8 arrays are generally quicker than on int64 arrays because less data is processed.
Additionally, some NumPy functions are optimized for specific data types. Using the correct data type can take advantage of these optimizations, leading to faster computation times.
Data Integrity:

Using the appropriate data type helps ensure data integrity. For example, if you have an array of counts, using an int type makes more sense than using a floating-point type, as counts are inherently whole numbers.
Incorrect data types can lead to unexpected results, such as integer overflow when the data type cannot hold the range of values.



Summary
In summary, determining the data type of elements in a NumPy array is straightforward using the .dtype attribute. Choosing the appropriate data type is crucial for efficient memory management and optimal performance in numerical computations, ensuring both speed and integrity in your data processing tasks.








 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

 Ans: In NumPy, **ndarrays** (N-dimensional arrays) are the core data structure used for storing and manipulating large datasets efficiently. They provide a powerful and flexible way to handle multi-dimensional data. Here’s an overview of ndarrays and their key features, along with a comparison to standard Python lists.

### Key Features of ndarrays

1. **Homogeneous Data**:
   - All elements in an ndarray are of the same data type, which allows for optimized storage and performance. This contrasts with Python lists, which can contain elements of varying types.

2. **Multi-dimensional**:
   - ndarrays can have any number of dimensions (1D, 2D, 3D, etc.), enabling representation of complex data structures such as matrices and tensors. This is more flexible than Python lists, which can become unwieldy for higher-dimensional data.

3. **Efficient Memory Usage**:
   - ndarrays are more memory-efficient than Python lists because they use a contiguous block of memory. This allows NumPy to reduce the overhead associated with storing multiple data types in lists.

4. **Vectorized Operations**:
   - NumPy supports element-wise operations on ndarrays without the need for explicit loops. This vectorization leads to faster computation and simpler code.

5. **Broadcasting**:
   - NumPy allows operations on arrays of different shapes through a feature called broadcasting, which automatically expands the smaller array to match the shape of the larger one. This is not natively supported in Python lists.

6. **Rich Functionality**:
   - ndarrays come with a wide array of built-in functions for mathematical operations, statistical analysis, linear algebra, and more, enabling complex data manipulation and analysis.

7. **Advanced Indexing and Slicing**:
   - NumPy provides sophisticated techniques for accessing and modifying data, such as boolean indexing and advanced slicing, which are more limited in Python lists.

### Differences from Standard Python Lists

1. **Data Type**:
   - **ndarrays**: Homogeneous (all elements must be of the same type).
   - **Python Lists**: Heterogeneous (elements can be of different types).

2. **Performance**:
   - **ndarrays**: More efficient for numerical operations due to optimized performance, leveraging low-level C and Fortran implementations.
   - **Python Lists**: Slower for numerical tasks, especially when dealing with large datasets.

3. **Functionality**:
   - **ndarrays**: Equipped with a vast library of mathematical functions and methods for advanced data manipulation.
   - **Python Lists**: Basic functionality; for advanced operations, you would need to use loops or other libraries.

4. **Memory Management**:
   - **ndarrays**: Use contiguous memory allocation, leading to better memory usage and access speed.
   - **Python Lists**: Use dynamic memory allocation, which can lead to overhead and fragmentation.

5. **Dimensionality**:
   - **ndarrays**: Can easily represent multi-dimensional data (2D matrices, 3D tensors, etc.).
   - **Python Lists**: While you can create nested lists to represent multi-dimensional data, it’s not as straightforward or efficient.

### Summary
ndarrays in NumPy are powerful, efficient structures for handling numerical data, with features designed to optimize performance and memory usage. They differ significantly from standard Python lists in terms of data type homogeneity, performance, and functionality, making them essential for scientific computing and data analysis tasks.

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Ans: NumPy arrays offer significant performance benefits over standard Python lists, especially when it comes to large-scale numerical operations. Here’s an analysis of these benefits:

1. Memory Efficiency
Contiguous Memory Allocation: NumPy arrays are stored in contiguous blocks of memory, which minimizes memory overhead and allows for more efficient use of cache memory. In contrast, Python lists store pointers to objects, which can lead to fragmentation and increased memory usage.
Homogeneous Data Types: Since all elements in a NumPy array are of the same type, NumPy can use a fixed amount of memory for each element. This uniformity allows for tighter packing of data, whereas Python lists can contain objects of varying sizes, increasing the memory footprint.
2. Performance of Operations
Vectorized Operations: NumPy allows for element-wise operations without the need for explicit loops. This vectorization leverages low-level optimizations and enables faster execution of operations. For example, adding two arrays element-wise can be done in a single operation with NumPy, while a Python list would require an explicit loop.

In [ ]:
import numpy as np

# NumPy array addition
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b  # Fast, vectorized operation

# Python list addition
list_a = [1, 2, 3]
list_b = [4, 5, 6]
c_list = [x + y for x, y in zip(list_a, list_b)]  # Slower, explicit loop


3. Reduced Overhead
Fewer Function Calls: NumPy functions are implemented in C, leading to reduced overhead compared to Python functions. Operations on NumPy arrays are executed in compiled code, which is significantly faster than the interpreted code of Python lists.
Batch Processing: NumPy allows for operations to be applied to entire arrays at once, which can reduce the number of function calls and improve performance.
4. Broadcasting
Automatic Expansion: NumPy's broadcasting feature allows for operations between arrays of different shapes, automatically expanding the smaller array to match the larger one. This capability can eliminate the need for manual replication of data, which would be computationally expensive and time-consuming with Python lists.
5. Optimized Mathematical Functions
Built-in Functions: NumPy provides a vast library of optimized mathematical functions (e.g., for linear algebra, Fourier transforms, and statistical calculations) that are specifically designed for performance. These functions operate on entire arrays at once, making them significantly faster than performing equivalent operations on Python lists.
6. Parallelization
Support for Multithreading: NumPy can take advantage of multi-core processors for certain operations, further enhancing performance on large datasets. Operations on Python lists, by contrast, are typically single-threaded unless explicitly parallelized through additional libraries.
Summary
Overall, NumPy arrays are designed for high performance with large-scale numerical operations. They provide improved memory efficiency, faster computation through vectorization, reduced overhead, and access to a rich set of optimized mathematical functions. These factors make NumPy the preferred choice for scientific computing, data analysis, and any application requiring heavy numerical computation compared to standard Python lists.






7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

Ans: The vstack() and hstack() functions in NumPy are used to stack arrays vertically and horizontally, respectively. Here’s a comparison of the two functions, along with examples to demonstrate their usage.

vstack()
Purpose: Stacks arrays in sequence vertically (row-wise).
Input: It takes a tuple of arrays and concatenates them along the first axis (axis 0).
Requirement: All input arrays must have the same shape along all dimensions except for the first one.
Example of vstack()

In [ ]:
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Stack the arrays vertically
result_vstack = np.vstack((array1, array2))
print("vstack result:")
print(result_vstack)


Output:

In [ ]:
vstack result:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


hstack()
Purpose: Stacks arrays in sequence horizontally (column-wise).
Input: It also takes a tuple of arrays and concatenates them along the second axis (axis 1).
Requirement: All input arrays must have the same shape along all dimensions except for the second one.
Example of hstack()

In [ ]:
# Stack the arrays horizontally
result_hstack = np.hstack((array1, array2))
print("hstack result:")
print(result_hstack)


Output:

In [ ]:
hstack result:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Summary of Differences
vstack() stacks arrays vertically (adding rows) and increases the number of rows.
hstack() stacks arrays horizontally (adding columns) and increases the number of columns.
These functions provide a convenient way to combine multiple arrays into a single array, making them useful for various data manipulation tasks in NumPy.

 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

 Ans: In NumPy, the fliplr() and flipud() methods are used to flip arrays along different axes. Here's a detailed explanation of their differences and effects on various array dimensions:

fliplr()
Purpose: Flips an array from left to right.
Axis: It operates along the second axis (axis 1), which corresponds to the columns of the array.
Effect: For 2D arrays, it reverses the order of the columns. For 1D arrays, it has no effect because there are no columns to flip.
Example of fliplr()

In [ ]:
import numpy as np

# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])

# Flip the array left to right
flipped_lr = np.fliplr(array_2d)
print("fliplr result:")
print(flipped_lr)


Output:

In [ ]:
fliplr result:
[[3 2 1]
 [6 5 4]]


flipud()
Purpose: Flips an array from up to down.
Axis: It operates along the first axis (axis 0), which corresponds to the rows of the array.
Effect: For 2D arrays, it reverses the order of the rows. For 1D arrays, it has no effect, as there are no rows to flip.
Example of flipud()

In [ ]:
# Flip the array up to down
flipped_ud = np.flipud(array_2d)
print("flipud result:")
print(flipped_ud)


Output:

In [ ]:
flipud result:
[[4 5 6]
 [1 2 3]]


Summary of Differences
Direction of Flip:

fliplr(): Flips arrays left to right (along columns).
flipud(): Flips arrays up to down (along rows).
Effect on Array Dimensions:

Both methods primarily affect 2D arrays. For 1D arrays, neither has any effect.
In a 2D array, fliplr() changes the order of elements in each row, while flipud() changes the order of the rows themselves.
Examples with Higher Dimensions
For 3D arrays, fliplr() flips along the last dimension (the columns of each 2D slice), while flipud() flips along the first dimension (the rows of each 2D slice).
This behavior continues for higher-dimensional arrays, where the flipping will occur along the specified axes.
These functions are useful for data manipulation tasks, such as image processing or rearranging data in specific ways for analysis.





 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

 Ans: The array_split() method in NumPy is a versatile function used to split an array into multiple sub-arrays. Here’s an overview of its functionality and how it manages uneven splits:

Functionality of array_split()
Purpose: To divide an array into multiple sub-arrays along a specified axis.
Syntax:

In [ ]:
numpy.array_split(ary, indices_or_sections, axis=0)


ary: The input array to be split.
indices_or_sections: This can either be an integer (specifying the number of equal splits) or a list of indices (specifying where to split).
axis: The axis along which to split the array (default is 0).
Key Features
Uneven Splits: Unlike split(), which requires equal-sized splits, array_split() can handle cases where the array cannot be evenly divided. It will distribute the elements as evenly as possible, with any remainder going into the first few sub-arrays.

Return Value: It returns a list of sub-arrays.

Handling Uneven Splits
When you specify the number of splits that does not evenly divide the array length, array_split() handles this by:

Creating as many equally-sized sub-arrays as possible.
Assigning any remaining elements to the initial sub-arrays until all elements are distributed.
Example of Uneven Splits

In [ ]:
import numpy as np

# Create a 1D array
array = np.array([1, 2, 3, 4, 5, 6, 7])

# Split the array into 3 parts
split_arrays = np.array_split(array, 3)
print("Result of array_split:")
for i, sub_array in enumerate(split_arrays):
    print(f"Sub-array {i}: {sub_array}")


In [ ]:
Result of array_split:
Sub-array 0: [1 2 3]
Sub-array 1: [4 5]
Sub-array 2: [6 7]


In this example:

The original array has 7 elements.
When splitting into 3 parts, the first sub-array contains 3 elements, the second contains 2 elements, and the third contains the remaining 2 elements.
Summary
Flexible Splitting: array_split() allows for flexible partitioning of arrays, accommodating uneven distributions without error.
Convenient for Various Use Cases: This functionality is particularly useful when dealing with datasets where the total number of elements may not be divisible by the desired number of splits, such as when processing batches of data or handling uneven distributions in data analysis tasks.




10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Ans: Vectorization and broadcasting are two fundamental concepts in NumPy that significantly enhance the efficiency of array operations. Here’s an explanation of each concept and how they contribute to performance improvements:

Vectorization
Definition: Vectorization refers to the process of applying operations to entire arrays (or large chunks of data) at once, rather than using explicit loops to iterate over elements. This approach leverages low-level optimizations and compiled code, allowing for faster execution.

Key Features:

Efficiency: By avoiding explicit Python loops, vectorization minimizes overhead and takes advantage of highly optimized C and Fortran routines in NumPy.
Conciseness: Vectorized operations lead to cleaner, more readable code. Instead of writing multiple lines of code to handle each element, you can perform operations in a single line.
Example:

In [ ]:
import numpy as np

# Create two large arrays
a = np.random.rand(1000000)
b = np.random.rand(1000000)

# Vectorized addition
c = a + b  # This adds the two arrays element-wise in a single operation


In this example, a + b performs element-wise addition without the need for a loop, resulting in faster execution.

Broadcasting
Definition: Broadcasting is a powerful mechanism that allows NumPy to perform arithmetic operations on arrays of different shapes and sizes. It automatically expands the smaller array along the axes where the dimensions differ, enabling element-wise operations even when the arrays don't have the same shape.

Key Features:

Automatic Alignment: When performing operations, NumPy compares the shapes of the arrays involved. If they are compatible, broadcasting adjusts the shapes to enable element-wise operations.
Memory Efficiency: Broadcasting does not create copies of the data. Instead, it creates a view of the original data, which minimizes memory usage.
Rules for Broadcasting:

If the arrays have different numbers of dimensions, the smaller-dimensional array is padded with ones on the left side.
If the dimensions are equal, the operation proceeds as usual.
If one of the dimensions is 1, it is stretched to match the other dimension.
Example:

In [ ]:
# Create a 2D array and a 1D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])

array_1d = np.array([10, 20, 30])

# Broadcasting: adding a 1D array to a 2D array
result = array_2d + array_1d
print(result)


Output:

In [ ]:
[[11 22 33]
 [14 25 36]]


In this example, the 1D array is broadcasted across the rows of the 2D array, allowing for element-wise addition without the need for explicit replication of the 1D array.

Contribution to Efficient Array Operations
Performance: Both vectorization and broadcasting reduce execution time by leveraging optimized, low-level implementations. This is especially important for large datasets, where the performance difference between vectorized operations and traditional looping can be significant.

Simplicity: They lead to cleaner and more maintainable code. Instead of complex loops, you can express operations in a straightforward manner, making the code easier to read and debug.

Memory Management: Broadcasting allows operations on arrays of different shapes without the overhead of creating large temporary arrays, which conserves memory.

Summary
Vectorization and broadcasting are key features of NumPy that enhance the performance and efficiency of numerical computations. By applying operations to entire arrays and enabling flexible shape compatibility, they make it possible to write concise, high-performance code for data manipulation and analysis.

                                             Practical Questions

 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

 Ans: You can create a 3x3 NumPy array with random integers between 1 and 100 using the np.random.randint() function. To interchange (or transpose) its rows and columns, you can use the .T attribute or the np.transpose() function. Here’s how you can do it:

In [ ]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array_3x3 = np.random.randint(1, 101, size=(3, 3))
print("Original array:")
print(array_3x3)

# Interchange rows and columns (transpose the array)
transposed_array = array_3x3.T
print("\nTransposed array:")
print(transposed_array)


Example Output:

In [ ]:
Original array:
[[42 18 63]
 [ 7 30 80]
 [95 37 12]]

Transposed array:
[[42  7 95]
 [18 30 37]
 [63 80 12]]


In this example:

A 3x3 array of random integers between 1 and 100 is created.
The array is then transposed, interchanging its rows and columns.

 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

 Ans: You can create a 1D NumPy array with 10 elements and then reshape it into a 2x5 array and a 5x2 array using the reshape() method. Here's how to do it:

In [ ]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)  # This creates an array with elements from 0 to 9
print("Original 1D array:")
print(array_1d)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped into 2x5 array:")
print(array_2x5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\nReshaped into 5x2 array:")
print(array_5x2)


Example Output:

In [ ]:
Original 1D array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped into 2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into 5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In this example:

The original 1D array contains integers from 0 to 9.
It is then reshaped first into a 2x5 array and subsequently into a 5x2 array, demonstrating the flexibility of reshaping in NumPy.




 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

Ans: You can create a 4x4 NumPy array with random float values using np.random.rand(), and then add a border of zeros around it using np.pad(). Here's how to do this:

In [ ]:
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)
print("Original 4x4 array:")
print(array_4x4)

# Add a border of zeros around the array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 array with a border of zeros:")
print(array_with_border)


Example Output:

In [ ]:
Original 4x4 array:
[[0.54207874 0.97151687 0.45370665 0.04412547]
 [0.95808058 0.71278074 0.77838812 0.63636864]
 [0.18080075 0.04918353 0.9058264  0.19727537]
 [0.50507415 0.66440762 0.32908526 0.89806929]]

6x6 array with a border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.54207874 0.97151687 0.45370665 0.04412547 0.        ]
 [0.         0.95808058 0.71278074 0.77838812 0.63636864 0.        ]
 [0.         0.18080075 0.04918353 0.9058264  0.19727537 0.        ]
 [0.         0.50507415 0.66440762 0.32908526 0.89806929 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In this example:

A 4x4 array of random float values is created.
The np.pad() function is used to add a border of zeros, resulting in a 6x6 array. The pad_width=1 argument specifies that a border of 1 unit is added around the original array. The mode='constant' with constant_values=0 specifies that the padding value is zero.

4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

Ans: You can create an array of integers from 10 to 60 with a step of 5 using the np.arange() function in NumPy. Here’s how to do it:

In [ ]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)
print("Array of integers from 10 to 60 with a step of 5:")
print(array)


Example Output:

In [ ]:
Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


In this example, np.arange(10, 61, 5) generates an array starting at 10 and ending at 60 (inclusive) with a step of 5.

 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

 Ans: You can create a NumPy array of strings and then apply various case transformations using string methods provided by NumPy. Here’s how to do it:

In [ ]:
import numpy as np

# Create a NumPy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(string_array)
lowercase_array = np.char.lower(string_array)
titlecase_array = np.char.title(string_array)

# Display the results
print("Original array:")
print(string_array)

print("\nUppercase transformation:")
print(uppercase_array)

print("\nLowercase transformation:")
print(lowercase_array)

print("\nTitle case transformation:")
print(titlecase_array)


Example Output:

In [ ]:
Original array:
['python' 'numpy' 'pandas']

Uppercase transformation:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase transformation:
['python' 'numpy' 'pandas']

Title case transformation:
['Python' 'Numpy' 'Pandas']


In this example:

The original array contains the strings 'python', 'numpy', and 'pandas'.
The np.char module is used to apply different case transformations: np.char.upper() for uppercase, np.char.lower() for lowercase, and np.char.title() for title case. Each transformation is applied to the entire array, demonstrating the power of NumPy's vectorized string operations.

 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

 Ans: You can generate a NumPy array of words and then insert a space between each character of every word using string operations. Here’s how to do it:

In [ ]:
import numpy as np

# Create a NumPy array of words
words_array = np.array(['hello', 'numpy', 'array'])

# Insert a space between each character of every word
spaced_words_array = np.char.join(' ', words_array)

# Display the results
print("Original array of words:")
print(words_array)

print("\nWords with spaces between characters:")
print(spaced_words_array)


Example Output:

In [ ]:
Original array of words:
['hello' 'numpy' 'array']

Words with spaces between characters:
['h e l l o' 'n u m p y' 'a r r a y']


In this example:

The original array contains the words 'hello', 'numpy', and 'array'.
The np.char.join(' ', words_array) function is used to insert a space between each character of the words, resulting in a new array with the modified words.




7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

Ans: You can create two 2D NumPy arrays and then perform element-wise addition, subtraction, multiplication, and division using standard arithmetic operators. Here’s how to do it:

In [ ]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

array2 = np.array([[10, 20, 30],
                    [40, 50, 60]])

# Perform element-wise addition
addition_result = array1 + array2

# Perform element-wise subtraction
subtraction_result = array1 - array2

# Perform element-wise multiplication
multiplication_result = array1 * array2

# Perform element-wise division
division_result = array1 / array2

# Display the results
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition_result)

print("\nElement-wise Subtraction:")
print(subtraction_result)

print("\nElement-wise Multiplication:")
print(multiplication_result)

print("\nElement-wise Division:")
print(division_result)


Example Output:

In [ ]:
Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[10 20 30]
 [40 50 60]]

Element-wise Addition:
[[11 22 33]
 [44 55 66]]

Element-wise Subtraction:
[[ -9 -18 -27]
 [-36 -45 -54]]

Element-wise Multiplication:
[[10 40 90]
 [160 250 360]]

Element-wise Division:
[[0.1        0.1        0.1       ]
 [0.1        0.1        0.1       ]]


In this example:

Two 2D arrays are created.
Element-wise operations (addition, subtraction, multiplication, and division) are performed using the respective arithmetic operators.
The results of each operation are displayed, showing how NumPy handles these operations efficiently on arrays.

 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

 Ans: You can create a 5x5 identity matrix using np.eye() and then extract its diagonal elements using np.diagonal(). Here’s how to do it:

In [ ]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


Example Output:

In [ ]:
5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In this example:

A 5x5 identity matrix is created, where the diagonal elements are all 1s and the rest are 0s.
The diagonal elements are then extracted, resulting in an array of ones corresponding to the diagonal of the identity matrix.




 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

 Ans: To generate a NumPy array of 100 random integers between 0 and 1000 and then find and display all the prime numbers from that array, you can use a helper function to check for primality. Here’s how to do it:

In [ ]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)
print("Random integers:")
print(random_integers)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = np.array([num for num in random_integers if is_prime(num)])

print("\nPrime numbers in the array:")
print(prime_numbers)


Example Output:

In [ ]:
Random integers:
[ 247  352  401  855  653  568  803  682  113  203 ...]  # (Sample output)

Prime numbers in the array:
[113  673  401  587]  # (Sample output)


In this code:

A NumPy array of 100 random integers between 0 and 1000 is created.
A helper function is_prime() checks whether a number is prime by testing divisibility.
A list comprehension is used to filter and collect all prime numbers from the array.
Finally, the prime numbers are displayed. Note that the actual prime numbers will vary each time you run the code because of the randomness in the generated integers.

 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.


To create a NumPy array representing daily temperatures for a month and then calculate and display the weekly averages, you can follow these steps:

Generate an array of temperatures for 30 days.
Reshape this array into a 4-week format (with 7 days each) and then compute the weekly averages.
Here’s how to do it:Ans: 

In [ ]:
import numpy as np

# Create a NumPy array representing daily temperatures for 30 days
daily_temperatures = np.random.uniform(low=15, high=35, size=30)  # Temperatures between 15 and 35 degrees
print("Daily Temperatures for the Month:")
print(daily_temperatures)

# Reshape the array to have 4 weeks (first 28 days)
weekly_temperatures = daily_temperatures[:28].reshape(4, 7)

# Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Display the weekly averages
print("\nWeekly Averages:")
for week, avg in enumerate(weekly_averages, start=1):
    print(f"Week {week}: {avg:.2f}°C")


Example Output:

In [ ]:
Daily Temperatures for the Month:
[25.13 20.45 30.26 22.99 18.54 31.77 28.67 29.76 23.11 20.67 27.43 19.28
 32.59 24.13 16.85 30.14 33.29 15.76 23.32 29.94 26.48 34.05 17.16 18.45
 30.81 31.92 19.66 20.90 28.17 25.55 24.05 29.12]

Weekly Averages:
Week 1: 24.98°C
Week 2: 24.34°C
Week 3: 25.04°C
Week 4: 23.84°C


In this example:

A 1D NumPy array of 30 daily temperatures is generated using np.random.uniform().
The first 28 days of temperatures are reshaped into a 4x7 array representing 4 weeks.
The weekly averages are calculated using np.mean() with axis=1 to get the average of each week.
Finally, the weekly averages are displayed in a formatted manner. The specific temperatures will vary each time you run the code due to randomness.